#!/bin/bash

source ../ENV_DEBUGGER
source ../ENV_LINUX_KERNEL
source ../ENV_LINUX_DRIVER

sed \
-e "s#LINUX_KERNEL_GDBPY#${LINUX_KERNEL_GDBPY}#g" \
-e "s#DEBUGGER_TARGET_SYSROOT#${DEBUGGER_TARGET_SYSROOT}#g" \
-e "s#LINUX_KERNEL_SOURCES#${LINUX_KERNEL_SOURCES}#g" \
-e "s#LINUX_DRIVER_SUBSPATH#${LINUX_DRIVER_SUBSPATH}#g" \
-e "s#LINUX_DRIVER_SOURCES#${LINUX_DRIVER_SOURCES}#g" \
-e "s#LINUX_DRIVER_PROBE_FUNC#${LINUX_DRIVER_PROBE_FUNC}#g" \
-e "s#LINUX_DRIVER_KO_HOSTDIR#${LINUX_DRIVER_KO_HOSTDIR}#g" \
-e "s#DEBUGGER_SERIAL_BAUDRATE#${DEBUGGER_SERIAL_BAUDRATE}#g" \
-e "s#DEBUGGER_SERIAL_DEVICE#${DEBUGGER_SERIAL_DEVICE}#g" \
gdbinit.inc > gdbinit
