#!/bin/bash

source ENV_TARGET
source ENV_LINUX_DRIVER

PROBE_CMD="modprobe ${LINUX_DRIVER_NAME} > /dev/null 2>&1 &"
DRIVER_PATH="${LINUX_DRIVER_KO_HOSTDIR}/${LINUX_DRIVER_NAME}.ko"

scp ${DRIVER_PATH} ${TARGET_SSH}:${LINUX_DRIVER_UPLOAD_PATH}
ssh ${TARGET_SSH} ${PROBE_CMD}
